---
# Tags applied to the Cloudformation stack
cf_tags:
  Stack: "project {{ project_tag }}"
  owner: "{{ email | default(user) | default('unknown') }}"
  config: "{{ config }}"
  guid: "{{ guid }}"
  uuid: "{{ uuid | default('none') }}"

# custom additional tags:
cloud_tags: {}

# How many times to try to create the cloudformation template
cloudformation_retries: 0
