---
aws_comment: Created by Ansible Agnostic Deployer V2
cloudformation_retries: 1

#################################################################
# VPC
#################################################################
aws_vpc_cidr: 192.168.0.0/16
aws_vpc_name: "{{ cluster_dns_zone }}"

#################################################################
# Subnet
#################################################################
aws_public_subnet_cidr: 192.168.0.0/24

#################################################################
# Security Groups
#################################################################
default_security_groups:
- name: BastionSG
  rules:
  - name: SSHPublic
    description: Public Access for bastions
    from_port: 22
    to_port: 22
    protocol: tcp
    cidr: "0.0.0.0/0"
    rule_type: Ingress
- name: DefaultSG
  rules:
  - name: FromBastionTCP
    description: Allow everything from Bastion
    from_port: 0
    to_port: 65535
    protocol: tcp
    from_group: BastionSG
    rule_type: Ingress
  - name: FromBastionUDP
    description: Allow everything from Bastion
    from_port: 0
    to_port: 65535
    protocol: tcp
    from_group: BastionSG
    rule_type: Ingress

# Environment specific security groups
security_groups: []

#################################################################
# DNS zones
#################################################################

# The top level DNS zone you want to update
# aws_dns_zone_root: "{{ subdomain_base_suffix | regex_replace('^\\.', '') }}."
aws_dns_zone_root: "{{ base_domain }}."

# Private DNS Zone dedicated to the environment
aws_dns_zone_private: "{{ guid }}.internal."
aws_dns_zone_private_chomped: "{{ aws_dns_zone_private | regex_replace('\\.$', '') }}"

# Public DNS Zone dedicated to the environment
aws_dns_zone_public: "{{ guid }}.{{ aws_dns_zone_root }}"
aws_dns_create_public_zone: true

aws_dns_ttl_public: 900
aws_dns_ttl_private: 3600

#################################################################
# Volumes
#################################################################

# default size for /dev/sda1
aws_default_rootfs_size: 50

# default Volume type
aws_default_volume_type: gp3

#################################################################
# Images
#################################################################

# changed to GOLD to save money via Red Hat Cloud Access program
aws_default_image: RHEL96GOLD

# When aws_template_generate_auto_select_availability_zone is set to true,
# the role will set aws_availability_zone to an availability that can host
# all instances types, unless several subnets are used.
aws_template_generate_auto_select_availability_zone: true
